# Cloudflare Pages configuration
# This file forces npm usage instead of bun

[build]
command = "npm ci && npm run build"
cwd = "."
watch_dir = "src"

[build.environment]
NODE_VERSION = "18"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"