// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljzwykusbmutghjtyeiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxqend5a3VzYm11dGdoanR5ZWlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMzk2MTEsImV4cCI6MjA2MjcxNTYxMX0.WyvzDacOCMLk4lKx6CyN3SOEswWP4LqMRQ-I6WWyF-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});